### ISSUE TITLE
Organization of some terms

### ISSUE THREAD

**Issue by Simone2021space** [angadhn/ComputationalDynamics#15]
The difference between bound and free vectors is well explained in chapter "Forces, Moments, and Torques ".

But should it also be introduced in the chapter "Vectors fundamentals"?

**Comment by mughees-asif** [comment]
@angadhn

**Comment by angadhn** [comment]
Nope; the knowledge of bound vectors is not particularly relevant at the level of kinematics IMO. It is because a force can be bound or unbound in how it acts. This ambiguous nature of a bound vector is not seen in the context of kinematics because linear velocity (and linear acceleration) is always bound; their angular parallels are not.
